# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: zendesk/jekyll-theme-zendesk-garden@main
# remote_theme: vaibhavvikas/jekyll-theme-minimalistic
# remote_theme: yaoyao-liu/minimal-light
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#show_downloads: false
# enable-grid-classes: true
# title: !
# description: We explore the development of the neonatal innate immune system.

title: ""
position: ""
affiliation: ""
email: ""

avatar: ./lab_logo.png

navigation:
  - text: Documentation
    internal: true
    url: ./docs


# navigation:
#   - name: Dr. Eniko Sajti's page
#     link: https://profiles.ucsd.edu/eniko.sajti
  #  sublist:
  #    - name: Image
  #      link: ./index.html#small-image
  # - name: Another Page
  #  link: ./another-page.html
  # - ...
#
# JB :
#  version : 0.3.0
