#remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: zendesk/jekyll-theme-zendesk-garden@main
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#show_downloads: false
title: Sajti lab at UC San Diego
description: We explore the development of the neonatal innate immune system.

sidebar:
  - getting-started
